added solution for the first project
rchermanteev/made-cpp-2020-hw pull request #4
Opened 2020-10-05 19:19 UTC by rchermanteev

У меня не получается побороть эту проблему(Can’t automatically merge). Я два раза всё удалял и делал всё по инструкции, проверяя каждый шаг. Мне не понятно из-за чего возникает эта ошибка.
Что бы уложится в дедлайн выкладываю так. Буду исправлять после ваших комментариев.

2020-10-18 00:24 UTC, xterrafunny requested changes

2020-10-18 00:24 UTC, xterrafunny commented on vector_operations/src/vector_ops.cpp
> +  vector<double> res_vec;
Зачем заставлять расширяться вектор, если размер уже известен

2020-10-18 00:24 UTC, xterrafunny commented on vector_operations/src/vector_ops.cpp
> +  return false;
Для этого есть тернарные операторы

2020-10-18 00:24 UTC, xterrafunny commented on vector_operations/src/vector_ops.cpp
> +  if ((a || b) && (sign(a[0]) == sign(b[0])))
Некорректно работает в случае, когда первые координаты нулевые

2020-10-18 00:24 UTC, xterrafunny commented on vector_operations/src/vector_ops.cpp
> +}
Есть `std::swap`

2020-10-19 21:26 UTC, rchermanteev commented
Здравствуйте! 
Я добавил исправления по замечаниям

2020-10-19 21:26 UTC, rchermanteev commented on vector_operations/src/vector_ops.cpp
> +  vector<double> res_vec;
Согласен. Добавил resize везде, где этого не было

2020-10-19 21:27 UTC, rchermanteev commented on vector_operations/src/vector_ops.cpp
> +  return false;
Поменял на тернарный оператор

2020-10-19 21:27 UTC, rchermanteev commented on vector_operations/src/vector_ops.cpp
> +  if ((a || b) && (sign(a[0]) == sign(b[0])))
Заменил на общий случай

2020-10-19 21:27 UTC, rchermanteev commented on vector_operations/src/vector_ops.cpp
> +}
Исправил :)

2020-10-29 15:35 UTC, Costello1329 commented
уберите merge конфликты и вмерджте сами, я аппрувлю

2020-10-29 15:40 UTC, Costello1329 approved these changes

2020-10-29 16:30 UTC, merged

2020-10-29 16:31 UTC, rchermanteev commented
Здравствуйте! Убрал merge конфликты